name: Security Audit

on:
  push:
    branches:
      - master
    paths:
      - "**/Cargo.toml"

permissions:
  contents: read

jobs:
  security-audit:
    permissions:
      checks: write # for rustsec/audit-check to create check
      contents: read # for actions/checkout to fetch code
      issues: write # for rustsec/audit-check to create issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Cargo.lock
        # https://github.com/rustsec/audit-check/issues/27
        run: cargo generate-lockfile

      - name: Audit Check
        # https://github.com/rustsec/audit-check/issues/2
        uses: rustsec/audit-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
